import Head from "next/head";
import ContactPage from "../components/ContactPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive Contact-Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <ContactPage />
    </div>
  );
}
